stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature-engineering:
    cmd: python src/feature-engineering.py
    deps:
    - data/interim
    - src/feature-engineering.py
    params:
    - feature-engineering.max_features
    outs:
    - data/processed
  model-training:
    cmd: python src/model-training.py
    deps:
    - data/processed
    - src/model-training.py
    params:
    - model-training.n_estimators
    - model-training.random_state
    outs:
    - models/model.pkl
  model-evaluation:
    cmd: python src/model-evaluation.py
    deps:
    - models/model.pkl
    - src/model-evaluation.py
    metrics:
    - reports/metrics.json
